import { SpeedInsights } from "@vercel/speed-insights/next"
import { Inter } from 'next/font/google'
import './globals.css'
import Providers from "../components/Providers";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Music',
  description: 'Generated by create next app',
  
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black text-white`}>
      <Providers>
           {children}
           <SpeedInsights/>
      </Providers>
        </body>
    </html>
  )
}

